---
svi_profiles:
  GENERIC:
    mtu: 1560
    enabled: true
  GENERIC_FULL:
    name: GENERIC Name
    mtu: 1560
    enabled: false
    ip_address_virtual: 10.1.10.254/24
  WITH_NO_MTU:
    enabled: true
  WITH_SNOOPING:
    enabled: true
    igmp_snooping_enabled: false

tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    # Optional example enabling multicast for tenant
    # Requires enabling of multicast in ATD_FABRIC.yml
    # evpn_l2_multicast:
    #   enabled: true
    #   underlay_l2_multicast_group_ipv4_pool: 232.0.0.0/20
    #   underlay_l2_multicast_group_ipv4_pool_offset: 2
    vrfs:
      Tenant_A_OP_Zone:
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          210:
            name: Tenant_A_OP_Zone_1
            tags: [ opzone ]
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          100:
            name: VLAN100
            tags: [ opzone ]
            enabled: true
            ip_address_virtual: 10.10.10.1/24
          200:
            name: VLAN200
            tags: [ special ]
            enabled: true
            ip_address_virtual: 20.20.20.1/24
    l2vlans:
      110:
        name: Extend
        tags: [ opzone ]
