# Spine Switches
spine:
  defaults:
    platform: CEOS-LAB
    bgp_as: 65001
    loopback_ipv4_pool: 192.0.255.0/24
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    mlag: false
  nodes:
    s1-spine1:
      id: 1
      mgmt_ip: 192.168.0.10/24
    s1-spine2:
      id: 2
      mgmt_ip: 192.168.0.11/24

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    platform: CEOS-LAB
    loopback_ipv4_pool: 192.0.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.0.254.0/24
    uplink_interfaces: [Ethernet2, Ethernet3]
    uplink_switches: [s1-spine1, s1-spine2]
    uplink_ipv4_pool: 172.30.255.0/24
    mlag_interfaces: [ Ethernet1, Ethernet6 ]
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    # filter:
    #   only_vlans_in_use: true
  node_groups:
    ATD_LEAF1-DC1:
      # filter: 
      #   tags: [ special, opzone ]
      bgp_as: 65101
      nodes:
        s1-leaf1:
          id: 1
          mgmt_ip: 192.168.0.12/24
          uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]
        s1-leaf2:
          id: 2
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces: [ Ethernet3, Ethernet3 ]
    ATD_LEAF2-DC1:
      # filter:
      #   tags: [ opzone ]
      bgp_as: 65102
      nodes:
        s1-leaf3:
          id: 3
          mgmt_ip: 192.168.0.14/24
          uplink_switch_interfaces: [ Ethernet4, Ethernet4 ]
        s1-leaf4:
          id: 4
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]
    ATD_BORDER-DC1:
      # filter: 
      #   tags: [ special, opzone ]
      bgp_as: 65103
      nodes:
        s1-brdr1:
          id: 5
          mgmt_ip: 192.168.0.100/24
          uplink_switch_interfaces: [ Ethernet7, Ethernet7 ]
          evpn_gateway:
            remote_peers:
              - hostname: s2-brdr1
            evpn_l2:
              enabled: true
            evpn_l3:
              enabled: true
              inter_domain: true
        s1-brdr2:
          id: 6
          mgmt_ip: 192.168.0.101/24
          uplink_switch_interfaces: [ Ethernet8, Ethernet8 ]